bench:
  dataset: wikimedia/wikipedia
  type: text
  preprocessing:
    chunk_overlap: 0
    chunk_size: 512
    chunktype: length
    dataset_ratio: 0.1
rag:
  action:
    preprocess: true
    embedding: false
    insert: true
    build_index: true
    reranking: false
    retrieval: false
    generation: false
    evaluate: false
  build_index:
    index_type: IVF_HNSW_SQ
    metric_type: L2
  embedding:
    device: cuda:0
    sentence_transformers_name: all-MiniLM-L6-v2
    batch_size: 1024
    embedding_framework: sentence_transformers
    model: nomic-ai/nomic-embed-text-v2-moe
    store: false
    load: true
    filepath: /home/shaobol2/RAGPipeline/wiki_entire.pickle
  insert:
    batch_size: 512
    collection_name: ''
    drop_previous_collection: false
run_name: default_run
sys:
  devices:
    cpu: cpu
    gpu_count: 2
    gpus:
    - cuda:0
    - cuda:1
  log:
    metrics_log: ./log/default_run.log
  vector_db:
    collection_name: 'lance_text_test' 
    db_path: /mnt/data1/shaobol2/lancedb # local path for lance db
    db_token: 
    drop_previous_collection: false
    type: lancedb